name: pypi-linux-test

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: clarabel
  PYTHON_VERSION: "3.7" # to build abi3 wheels
  PYPI_TARGET: pypi # use "testpypi" for testing, "pypi" otherwise

# NB: uncomment "if" lines below to skip compilation except on version tagging

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
       matrix:
        #target: [x86_64, aarch64]
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system libraries
        run: |
          sudo apt update
          sudo apt install -y pkg-config libssl-dev 

      - name: Install openblas 
        run: |
          sudo apt install -y libopenblas-dev

      - name: Install gfortran
        run: |
          sudo apt install -y gfortran
          sudo apt install -y gfortran-aarch64-linux-gnu

      - name: Dump env
        run: |
          env

      - name: Direct cargo build
        env:
          RUST_BACKTRACE: '1'
        run: |
          cargo build -v --release --features "sdp-openblas,openblas-src/system,openssl/vendored"
          cargo test

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        env:
          RUST_BACKTRACE: '1'
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: -v --release --out dist -i python${{ env.PYTHON_VERSION }} --features "_pypi_config_linux"

      - name: Install and test built wheel
        run: |
          python -m pip install dist/${{ env.PACKAGE_NAME }}-*.whl --force-reinstall
          python -c "import clarabel"
          python examples/python/example_qp.py 
          python examples/python/example_sdp.py 

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

